Add the DataSource caption property
mendix/widgets-tools pull request #24
Opened 2023-01-18 10:16 UTC by hendrik-jacobs-mendix

## Checklist

-   Contains unit tests ❌
-   Contains breaking changes ❌
-   Compatible with: MX 9️⃣
-   Did you update version and changelog? ❌
-   PR title properly formatted (`[XX-000]: description`)? ✅

## This PR contains

-   [ ] Bug fix
-   [x] Feature
-   [ ] Refactor
-   [ ] Documentation
-   [ ] Other (describe)

## What is the purpose of this PR?

This PR adds a caption field to the DataSource so that custom widgets have access to DataSource caption as is used in the Page Explorer when generating previews for the page editor.

## Relevant changes

Updated the typings generator for GetPreview

## What should be covered while testing?

Widgets should be able to understand the DataSource caption when generating a preview for the page editor

2023-01-18 12:27 UTC, tamelbrun commented
@hendrik-jacobs-mendix Can you mention the Mendix version number where this feature was added?

2023-01-18 12:30 UTC, hendrik-jacobs-mendix commented
Sure, I've added it to the description, but just to make sure it doesn't get lost, we predict that it should be released as part of version 9.23

2023-02-15 15:50 UTC, tamelbrun commented
@hendrik-jacobs-mendix Can you add a changelog entry under `[Unreleased]` and bump the version to `9.23.0`? (You diligently set that item in the checklist to ❌, but it's a checklist for a reason. ;))

2023-02-15 15:53 UTC, tamelbrun requested changes
Changelog entry + version bump needed

2023-02-15 16:26 UTC, hendrik-jacobs-mendix commented
I think we'll need to move this to 9.24 as well, as the corresponding change in Studio Pro didn't make the 9.23 freeze

2023-02-15 17:10 UTC, tamelbrun requested changes

2023-02-15 17:10 UTC, tamelbrun commented on packages/pluggable-widgets-tools/CHANGELOG.md
> +- We add the new data source caption to the typings generator.
This needs to be more specific, as the caption of a data source is part of the _preview_ typings. We also make it a habit to explicitly mention the Mendix version in which a feature was added (which is usually the same as the version of the tools, but not necessarily).

2023-02-20 09:37 UTC, tamelbrun commented on packages/pluggable-widgets-tools/CHANGELOG.md
> +- We add the new data source caption to the typings generator.
@hendrik-jacobs-mendix Can you also bump the version in the package.json to 9.24.0, as promised in the PR description? ;)

2023-02-20 09:56 UTC, tamelbrun requested changes
We do not allow merge commits in a PR.

2023-02-20 10:31 UTC, tamelbrun approved these changes

2023-02-20 10:32 UTC, tamelbrun requested changes
Unit test coverage is missing.

2023-02-20 12:08 UTC, tamelbrun commented on packages/pluggable-widgets-tools/CHANGELOG.md
> +- We add the new data source caption to the typings generator.
✔️

2023-02-20 16:29 UTC, tamelbrun approved these changes

2023-03-02 09:11 UTC, hendrik-jacobs-mendix commented
I rebased on the 9.23 version changes

2023-03-02 10:43 UTC, jeffersonRibeiro commented
I noticed that the Script Tests are passing too fast 🤔. In fact, the Script tests are being skipped. We may have a problem with the repo workflow setup. The only difference I noticed is that your MR points to `mendix:master` instead of just `master`. Not sure if that's the reason. I'll have to investigate further. This problem is also happening with the other opened MRs, they also points to `mendix:master`

2023-03-06 12:44 UTC, hendrik-jacobs-mendix commented
Rebased onto the latest changes

2023-03-23 14:27 UTC, jeffersonRibeiro commented
> I noticed that the Script Tests are passing too fast 🤔. In fact, the Script tests are being skipped. We may have a problem with the repo workflow setup and repository forks. The only difference I noticed is that your MR points to `mendix:master` instead of just `master`. Not sure if that's the reason. I'll have to investigate further. This problem is also happening with the other opened MRs, they also points to `mendix:master`

@hendrik-jacobs-mendix This problem was fixed and merged into master.

Could you please rebase your branch?

2023-03-23 15:58 UTC, jeffersonRibeiro approved these changes

2023-03-24 08:53 UTC, merged