[PAG-2309] Add support for render modes on pluggable widgets
mendix/widgets-tools pull request #92
Opened 2024-04-29 11:47 UTC by hendrik-jacobs-mendix

## Checklist

-   Contains unit tests ✅
-   Contains breaking changes ❌
-   Compatible with: MX 10
-   Did you update version and changelog? ✅
-   PR title properly formatted (`[XX-000]: description`)? ✅

## This PR contains

-   [ ] Bug fix
-   [X ] Feature
-   [ ] Refactor
-   [ ] Documentation
-   [ ] Other (describe)

## What is the purpose of this PR?
This PR will introduce a new parameter to the generated pluggable widgets that will allow users to change the rendering according to which mode the canvas is currently in.

## Relevant changes
Add a field to the generator for pluggable widget preview properties that can take one of 3 values, namely "xray", "design" and "structure"

## What should be covered while testing?
Check that generated widget preview properties has the "renderMode: "xray", "design", "structure";" property added

2024-05-01 15:27 UTC, LEGIO-SEXTA-FERRATA commented on packages/pluggable-widgets-tools/CHANGELOG.md
> +- We added the renderMode parameter to the preview arguments. This flag will give developers the ability to customize the preview for different render modes namnely x-ray, structure and design.
There is a typo here. I think **namnely** should become namely.

2024-05-02 09:09 UTC, legio-vi-ferrata approved these changes
Approved. 👍🏻

2024-07-09 10:00 UTC, weirdwater requested changes
Hi @hendrik-jacobs-mendix,

Thanks for the PR and sorry for the late review. We have added some comments.

2024-07-09 10:00 UTC, weirdwater commented on packages/pluggable-widgets-tools/package.json
> +  "version": "10.7.3",
This can be omitted as the version is bumped in an action during the release process.

2024-07-09 10:00 UTC, weirdwater commented on packages/pluggable-widgets-tools/src/typings-generator/generatePreviewTypes.ts
> +     * Introduced in version 10.11.0 otherwise it will be undefined
We like the idea of including JSDocs for generated properties (we already do it for deprecated or beta properties) but in this case we would prefer to leave it out. The comment does not describe the utility/semantics of the property and the type already communicates that it may be undefined.

2024-07-09 12:58 UTC, weirdwater approved these changes
Thanks for the changes.

2024-07-09 13:30 UTC, closed without merging

2024-07-10 07:28 UTC, weirdwater commented
Merged with #93